### PR TITLE
Fix mistakes in 4 files

### PR DESCRIPTION
**Pull request by AndreasCag**
Here is mistake fixes.

P.S. I can't understand why change one line overwrite hundred lines. Is it normal? 
If exist some better practice and I do something wrong you can notify me.

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/classes.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/dotnet-new/csharp/classes?branch=pr-ru-ru-24) | [Details](#user-content-docs%2Fcsharp%2Fclasses.md)
[docs/csharp/delegate-class.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/delegate-class.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ru-ru/dotnet-new/csharp/delegate-class?branch=pr-ru-ru-24) | [Details](#user-content-docs%2Fcsharp%2Fdelegate-class.md)
[docs/csharp/basic-types.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/basic-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/dotnet-new/csharp/basic-types?branch=pr-ru-ru-24) |
[docs/csharp/codedoc.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/codedoc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/dotnet-new/csharp/codedoc?branch=pr-ru-ru-24) |

<a name="docs%2Fcsharp%2Fclasses.md"></a>
### [docs/csharp/classes.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/classes.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/docs/standard/garbagecollection/gc.md).

<a name="docs%2Fcsharp%2Fdelegate-class.md"></a>
### [docs/csharp/delegate-class.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/delegate-class.md)
 - **Line 41**: **[Warning]** Invalid file link:(~/docs/csharp/generics.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C31%5C0def0b02-9e70-9a3f-539b-c2a9f67cb533%5CPullRequest%5C201705310715393750-24%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by yeremee** [comment]
Sign the CLA at https://cla2.dotnetfoundation.org to remove red `cla-required` label.

**Comment by AndreasCag** [comment]
Hmm, I did the [following steps](https://support.docusign.com/articles/How-do-I-sign-a-DocuSign-document-Basic-Signing) except step 8 first time 31 may, with step 8 second time 6 june and third time 7 june.
But it seems that something going wrong.
I didn't think it would be a problem, but it is.

SIGN_1
--
SIGN_2

**Comment by gosali** [comment]
Hi @AndreasCag , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@AndreasCag , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Please bear in mind for future opportunities that the correct way to submit a new PR is modifying only one file per PR. Otherwise the PR will be rejected and close. Sorry for this inconvenience

Microsoft C&E Localization Team

**Pull request merged**
