### PR TITLE
Update preprocessor-elif.md

### PR DESCRIPTION
**Pull request by AndreasCag**
Fix translation

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/preprocessor-directives/preprocessor-elif.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-3/docs/csharp/language-reference/preprocessor-directives/preprocessor-elif.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-elif?branch=pr-ru-ru-32) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C1%5C0def0b02-9e70-9a3f-539b-c2a9f67cb533%5CPullRequest%5C201707011332321173-32%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/preprocessor-directives/preprocessor-elif.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-3/docs/csharp/language-reference/preprocessor-directives/preprocessor-elif.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-elif?branch=pr-ru-ru-32) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C1%5C0def0b02-9e70-9a3f-539b-c2a9f67cb533%5CPullRequest%5C201707011358029880-32%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/preprocessor-directives/preprocessor-elif.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-3/docs/csharp/language-reference/preprocessor-directives/preprocessor-elif.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-elif?branch=pr-ru-ru-32) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C1%5C0def0b02-9e70-9a3f-539b-c2a9f67cb533%5CPullRequest%5C201707011358139326-32%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @AndreasCag , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@AndreasCag , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
