### PR TITLE
Fix mistakes in async-in-depth.md

### PR DESCRIPTION
**Pull request by AndreasCag**
Fix mistakes on lines 26, 35 and 81.

### CODE REVIEW

**Comment by olprod** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/programming-guide/classes-and-structs/how-to-create-a-new-method-for-an-enumeration.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-create-a-new-method-for-an-enumeration.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-create-a-new-method-for-an-enumeration.md)
[docs/csharp/programming-guide/classes-and-structs/how-to-implement-and-call-a-custom-extension-method.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-implement-and-call-a-custom-extension-method.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-implement-and-call-a-custom-extension-method.md)
[docs/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-initialize-a-dictionary-with-a-collection-initializer.md)
[docs/csharp/programming-guide/classes-and-structs/how-to-return-subsets-of-element-properties-in-a-query.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-return-subsets-of-element-properties-in-a-query.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-return-subsets-of-element-properties-in-a-query.md)
[docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-checksum.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-checksum.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Flanguage-reference%2Fpreprocessor-directives%2Fpreprocessor-pragma-checksum.md)
[docs/csharp/programming-guide/concepts/linq/linq-to-adonet-portal-page.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/concepts/linq/linq-to-adonet-portal-page.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fconcepts%2Flinq%2Flinq-to-adonet-portal-page.md)
[docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fconcepts%2Flinq%2Fdata-transformations-with-linq.md)
[docs/visual-basic/developing-apps/programming/drives-directories-files/basics-of-net-framework-file-io-and-the-file-system.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/visual-basic/developing-apps/programming/drives-directories-files/basics-of-net-framework-file-io-and-the-file-system.md) | :x:Error | | [Details](#user-content-docs%2Fvisual-basic%2Fdeveloping-apps%2Fprogramming%2Fdrives-directories-files%2Fbasics-of-net-framework-file-io-and-the-file-system.md)
[docs/framework/migration-guide/how-to-determine-which-net-framework-updates-are-installed.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/framework/migration-guide/how-to-determine-which-net-framework-updates-are-installed.md) | :x:Error | | [Details](#user-content-docs%2Fframework%2Fmigration-guide%2Fhow-to-determine-which-net-framework-updates-are-installed.md)
[docs/csharp/language-reference/compiler-options/win32manifest-compiler-option.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/language-reference/compiler-options/win32manifest-compiler-option.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Flanguage-reference%2Fcompiler-options%2Fwin32manifest-compiler-option.md)
[docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fconcepts%2Flinq%2Fintroduction-to-linq-queries.md)
[docs/csharp/programming-guide/interop/walkthrough-office-programming.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/interop/walkthrough-office-programming.md) | :x:Error | | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Finterop%2Fwalkthrough-office-programming.md)
[docs/standard/async-in-depth.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/standard/async-in-depth.md) | :warning:Warning | | [Details](#user-content-docs%2Fstandard%2Fasync-in-depth.md)

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-create-a-new-method-for-an-enumeration.md"></a>
### [docs/csharp/programming-guide/classes-and-structs/how-to-create-a-new-method-for-an-enumeration.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-create-a-new-method-for-an-enumeration.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vs_current_short](../../../csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md)]&quot; at line 49: Couldn&#39;t find file docs/csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-implement-and-call-a-custom-extension-method.md"></a>
### [docs/csharp/programming-guide/classes-and-structs/how-to-implement-and-call-a-custom-extension-method.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-implement-and-call-a-custom-extension-method.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vs_current_short](../../../csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md)]&quot; at line 61: Couldn&#39;t find file docs/csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Warning]** Invalid cross reference &quot;&amp;lt;xref:System.String&amp;gt;&quot;.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-initialize-a-dictionary-with-a-collection-initializer.md"></a>
### [docs/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-initialize-a-dictionary-with-a-collection-initializer.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vs_current_short](../../../csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md)]&quot; at line 48: Couldn&#39;t find file docs/csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Warning]** Invalid cross reference &quot;&amp;lt;xref:System.Collections.Generic.Dictionary`2&amp;gt;&quot;, &quot;&amp;lt;xref:System.Collections.Generic.Dictionary`2.Add*&amp;gt;&quot;.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fclasses-and-structs%2Fhow-to-return-subsets-of-element-properties-in-a-query.md"></a>
### [docs/csharp/programming-guide/classes-and-structs/how-to-return-subsets-of-element-properties-in-a-query.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/classes-and-structs/how-to-return-subsets-of-element-properties-in-a-query.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vs_current_short](../../../csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md)]&quot; at line 68: Couldn&#39;t find file docs/csharp/programming-guide/classes-and-structs/includes/vs_current_short_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **Line 73**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

<a name="docs%2Fcsharp%2Flanguage-reference%2Fpreprocessor-directives%2Fpreprocessor-pragma-checksum.md"></a>
### [docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-checksum.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-checksum.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecasp](../../../csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md)]&quot; at line 39: Couldn&#39;t find file docs/csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecasp](../../../csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md)]&quot; at line 60: Couldn&#39;t find file docs/csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecasp](../../../csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md)]&quot; at line 60: Couldn&#39;t find file docs/csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecasp](../../../csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md)]&quot; at line 62: Couldn&#39;t find file docs/csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fconcepts%2Flinq%2Flinq-to-adonet-portal-page.md"></a>
### [docs/csharp/programming-guide/concepts/linq/linq-to-adonet-portal-page.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/concepts/linq/linq-to-adonet-portal-page.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecado](../../../../csharp/programming-guide/concepts/linq/includes/vstecado_md.md)]&quot; at line 30: Couldn&#39;t find file docs/csharp/programming-guide/concepts/linq/includes/vstecado_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecado](../../../../csharp/programming-guide/concepts/linq/includes/vstecado_md.md)]&quot; at line 38: Couldn&#39;t find file docs/csharp/programming-guide/concepts/linq/includes/vstecado_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecado](../../../../csharp/programming-guide/concepts/linq/includes/vstecado_md.md)]&quot; at line 38: Couldn&#39;t find file docs/csharp/programming-guide/concepts/linq/includes/vstecado_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Warning]** Invalid cross reference &quot;&amp;lt;xref:System.Data.DataSet&amp;gt;&quot;.
 - **Line 42**: **[Warning]** Invalid file link:(~/docs/framework/data/adonet/linq-to-dataset.md).
 - **Line 52**: **[Warning]** Invalid file link:(~/docs/framework/data/adonet/ef/language-reference/linq-to-entities.md).

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fconcepts%2Flinq%2Fdata-transformations-with-linq.md"></a>
### [docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecado](../../../../csharp/programming-guide/concepts/linq/includes/vstecado_md.md)]&quot; at line 91: Couldn&#39;t find file docs/csharp/programming-guide/concepts/linq/includes/vstecado_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **Line 123**: **[Warning]** Invalid file link:(~/docs/framework/data/adonet/sql/linq/stored-procedures.md).
 - **Line 130**: **[Warning]** Invalid file link:(~/docs/framework/data/adonet/linq-to-dataset.md).
 - **Line 132**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

<a name="docs%2Fvisual-basic%2Fdeveloping-apps%2Fprogramming%2Fdrives-directories-files%2Fbasics-of-net-framework-file-io-and-the-file-system.md"></a>
### [docs/visual-basic/developing-apps/programming/drives-directories-files/basics-of-net-framework-file-io-and-the-file-system.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/visual-basic/developing-apps/programming/drives-directories-files/basics-of-net-framework-file-io-and-the-file-system.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecasp](../../../../csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md)]&quot; at line 107: Couldn&#39;t find file docs/csharp/language-reference/preprocessor-directives/includes/vstecasp_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Warning]** Invalid cross reference &quot;&amp;lt;xref:System.IO&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.File&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.Directory&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.FileInfo&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.DirectoryInfo&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.Stream&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.FileStream&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.IsolatedStorage.IsolatedStorageFileStream&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.BufferedStream&amp;gt;&quot;, &quot;&amp;lt;xref:System.Security.Cryptography.CryptoStream&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.MemoryStream&amp;gt;&quot;, &quot;&amp;lt;xref:System.Net.Sockets.NetworkStream&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.FileAccess&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.FileMode&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.FileShare&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.FileAttributes&amp;gt;&quot;, &quot;&amp;lt;xref:System.Security.Permissions.FileIOPermission&amp;gt;&quot;, &quot;&amp;lt;xref:System.IO.FileSystemWatcher&amp;gt;&quot;.
 - **Line 48**: **[Warning]** Invalid file link:(~/docs/visual-basic/language-reference/statements/imports-statement-net-namespace-and-type.md).

<a name="docs%2Fframework%2Fmigration-guide%2Fhow-to-determine-which-net-framework-updates-are-installed.md"></a>
### [docs/framework/migration-guide/how-to-determine-which-net-framework-updates-are-installed.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/framework/migration-guide/how-to-determine-which-net-framework-updates-are-installed.md)
 - **Line 47**: **[Error]** Unable to resolve  [!code-csharp[ListUpdates#1](../../../samples/snippets/csharp/VS_Snippets_CLR/listupdates/cs/program.cs#1)] [!code-vb[ListUpdates#1](../../../samples/snippets/visualbasic/VS_Snippets_CLR/listupdates/vb/program.vb#1)]  

. Can not find reference ../../../samples/snippets/csharp/VS_Snippets_CLR/listupdates/cs/program.cs#1)] [!code-vb[ListUpdates.
 - **Line 30**: **[Warning]** Invalid file link:(~/docs/framework/install/guide-for-developers.md).
 - **Line 81**: **[Warning]** Invalid file link:(~/docs/framework/install/guide-for-developers.md).

<a name="docs%2Fcsharp%2Flanguage-reference%2Fcompiler-options%2Fwin32manifest-compiler-option.md"></a>
### [docs/csharp/language-reference/compiler-options/win32manifest-compiler-option.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/language-reference/compiler-options/win32manifest-compiler-option.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csharp_current_short](../../../csharp/language-reference/compiler-options/includes/csharp_current_short_md.md)]&quot; at line 54: Couldn&#39;t find file docs/csharp/language-reference/compiler-options/includes/csharp_current_short_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fconcepts%2Flinq%2Fintroduction-to-linq-queries.md"></a>
### [docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[vstecado](../../../../csharp/programming-guide/concepts/linq/includes/vstecado_md.md)]&quot; at line 45: Couldn&#39;t find file docs/csharp/programming-guide/concepts/linq/includes/vstecado_md.md. Fallback folders: W:\ogha-s\_repo.en-us\.
 - **[Warning]** Invalid cross reference &quot;&amp;lt;xref:System.Collections.Generic.IEnumerable%601&amp;gt;&quot;, &quot;&amp;lt;xref:System.Collections.IEnumerable&amp;gt;&quot;, &quot;&amp;lt;xref:System.Linq.IQueryable%601&amp;gt;&quot;, &quot;&amp;lt;xref:System.Xml.Linq.XElement&amp;gt;&quot;, &quot;&amp;lt;xref:System.Collections.ArrayList&amp;gt;&quot;, &quot;&amp;lt;xref:System.Linq.Enumerable.ToList%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.Linq.Enumerable.ToArray%2A&amp;gt;&quot;.
 - **Line 62**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/concepts/linq/media/linq_query.png).
 - **Line 91**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).
 - **Line 122**: **[Warning]** Invalid file link:(~/docs/csharp/programming-guide/linq-query-expressions/index.md).

<a name="docs%2Fcsharp%2Fprogramming-guide%2Finterop%2Fwalkthrough-office-programming.md"></a>
### [docs/csharp/programming-guide/interop/walkthrough-office-programming.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/csharp/programming-guide/interop/walkthrough-office-programming.md)
 - **Line 86**: **[Error]** Unable to resolve  [!code-cs[csOfficeWalkthrough#1](../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_1.cs)]  [!code-vb[csOfficeWalkthrough#1](../../../csharp/programming-guide/interop/codesnippet/VisualBasic/walkthrough-office-programming_1.vb)]  

. Can not find reference ../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_1.cs)]  [!code-vb[csOfficeWalkthrough.
 - **Line 94**: **[Error]** Unable to resolve  [!code-cs[csOfficeWalkthrough#2](../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_2.cs)]  [!code-vb[csOfficeWalkthrough#2](../../../csharp/programming-guide/interop/codesnippet/VisualBasic/walkthrough-office-programming_2.vb)]  
. Can not find reference ../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_2.cs)]  [!code-vb[csOfficeWalkthrough.
 - **Line 98**: **[Error]** Unable to resolve  [!code-cs[csOfficeWalkthrough#3](../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_3.cs)]  [!code-vb[csOfficeWalkthrough#3](../../../csharp/programming-guide/interop/codesnippet/VisualBasic/walkthrough-office-programming_3.vb)]  

. Can not find reference ../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_3.cs)]  [!code-vb[csOfficeWalkthrough.
 - **Line 104**: **[Error]** Unable to resolve  [!code-cs[csOfficeWalkthrough#4](../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_4.cs)]  [!code-vb[csOfficeWalkthrough#4](../../../csharp/programming-guide/interop/codesnippet/VisualBasic/walkthrough-office-programming_4.vb)]  

. Can not find reference ../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_4.cs)]  [!code-vb[csOfficeWalkthrough.
 - **Line 126**: **[Error]** Unable to resolve  [!code-cs[csOfficeWalkthrough#7](../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_7.cs)]  [!code-vb[csOfficeWalkthrough#7](../../../csharp/programming-guide/interop/codesnippet/VisualBasic/walkthrough-office-programming_7.vb)]  

. Can not find reference ../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_7.cs)]  [!code-vb[csOfficeWalkthrough.
 - **Line 140**: **[Error]** Unable to resolve  [!code-cs[csOfficeWalkthrough#9](../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_9.cs)]  [!code-vb[csOfficeWalkthrough#9](../../../csharp/programming-guide/interop/codesnippet/VisualBasic/walkthrough-office-programming_9.vb)]  
. Can not find reference ../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_9.cs)]  [!code-vb[csOfficeWalkthrough.
 - **Line 148**: **[Error]** Unable to resolve  [!code-cs[csOfficeWalkthrough#10](../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_10.cs)]  [!code-vb[csOfficeWalkthrough#10](../../../csharp/programming-guide/interop/codesnippet/VisualBasic/walkthrough-office-programming_10.vb)]  

. Can not find reference ../../../csharp/programming-guide/interop/codesnippet/CSharp/walkthrough-office-programming_10.cs)]  [!code-vb[csOfficeWalkthrough.
 - **Line 92**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/procedures/auto-implemented-properties.md).
 - **Line 96**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/collection-initializers/index.md).
 - **Line 138**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/procedures/lambda-expressions.md).
 - **Line 170**: **[Warning]** Invalid file link:(~/docs/framework/app-domains/how-to-view-assembly-contents.md).
 - **Line 200**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/procedures/auto-implemented-properties.md).
 - **Line 202**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/collection-initializers/index.md).
 - **Line 204**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/procedures/optional-parameters.md).
 - **Line 205**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/procedures/passing-arguments-by-position-and-by-name.md).
 - **Line 207**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/early-late-binding/index.md).
 - **Line 210**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/language-features/procedures/lambda-expressions.md).
 - **Line 216**: **[Warning]** Invalid file link:(~/docs/visual-basic/programming-guide/com-interop/index.md).

<a name="docs%2Fstandard%2Fasync-in-depth.md"></a>
### [docs/standard/async-in-depth.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-1/docs/standard/async-in-depth.md)
 - **[Warning]** Invalid cross reference &quot;[TaskCompletionSource](xref:System.Threading.Tasks.TaskCompletionSource%601.SetResult(%600))&quot;, &quot;[Task&amp;amp;lt;T&amp;amp;gt;](xref:System.Threading.Tasks.Task%601)&quot;.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C28%5C0def0b02-9e70-9a3f-539b-c2a9f67cb533%5CPullRequest%5C201705281820590998-22%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AndreasCag** [comment]
I'm concerned. Why there are so many errors?

**Comment by v-radelg** [comment]
Hi @AndreasCag , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@AndreasCag  Thank you for your feedback and suggestion! 
		
The suggestion has been accepted but We found that you Submited the PR on the Master branch which is not fully aligned with our acceptance criterial, I am closing this PR now. 
Could you please re open it on the [Live branch](https://github.com/dotnet/docs.ru-ru/blob/live/docs/standard/async-in-depth.md) ?
		
Microsoft C&E Localization Team

**Pull request closed without merging**
