### PR TITLE
Update preprocessor-line.md

### PR DESCRIPTION
**Pull request by AndreasCag**

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/language-reference/preprocessor-directives/preprocessor-line.md](https://github.com/AndreasCag/docs.ru-ru/blob/patch-4/docs/csharp/language-reference/preprocessor-directives/preprocessor-line.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-line?branch=pr-ru-ru-33) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C1%5C0def0b02-9e70-9a3f-539b-c2a9f67cb533%5CPullRequest%5C201707011414257189-33%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AndreasCag** [comment]
Please, pay your attention to [line №44](https://github.com/dotnet/docs.ru-ru/pull/33/commits/e50dac7efd4bb843a165534e6622ec8f82bb6eef#diff-7b2ada8e60e910ec14ed9288c56cab97R44).
At the end of the line there is the phrase:

> **source generators**

which had been translated to:

> **генераторы источника**

I translated it to:

> **генераторы исходного кода**

But i doubt about correct translation.

**Comment by v-radelg** [comment]
Hi @AndreasCag , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@AndreasCag , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
