### PR TITLE
fixing broken toc link

### PR DESCRIPTION
**Pull request by mairaw**
@nokura

### CODE REVIEW

**Comment by mairaw** [comment]
ping @nokura @gosali

**Comment by nokura** [comment]
Sorry for the delay. We are working on it an will resolve soon.

**Comment by gosali** [comment]
@nokura   We are checking this with the Production team.

@mairaw Do you have a the website where this TOC is incorrectly showed?

Thank you in advance.
Regards

**Comment by gosali** [comment]
@mairaw @nokura , Thank you for your feedback and suggestion! 
  
The suggestion will be merged to the production, we will re-release this articles in the next loc release round. 
  
Microsoft C&E Localization Team

**Pull request merged**
