### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by grainhomeg**
Исправлено расположение элементов.

### CODE REVIEW

**Comment by gosali** [comment]
@grainhomeg Could you please re submitt your PR on the live branch so we can process it?

Thank you in advance

**Comment by mairaw** [comment]
I changed the base for you @gosali

**Comment by gosali** [comment]
@mairaw Thank you a lot!

**Comment by v-radelg** [comment]
Hello @grainhomeg  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hello, @grainhomeg,  Thank you for your feedback and suggestion.    The English source file has been updated recently. Your feedback will be considered when localizing the new version.  Many thanks for your contribution.  Kind regards,  Microsoft C&E Localization Team

**Pull request closed without merging**
